name: "Business Task"
description: "ビジネスチーム用タスク管理テンプレート"
title: "[TASK] "
labels:
  - todo
body:
  - type: markdown
    attributes:
      value: |
        ## 📈 ビジネスタスク

        このテンプレートを使用して事業開発・セールス・マーケティング・法務・財務・人事などのタスクを作成してください。
        完了時は該当ラベルを適用し、成果物 URL を **必ず** 記載してください。

  - type: input
    id: problem_goal
    attributes:
      label: "🎯 Problem / Goal"
      description: "解決する課題や目的を明確に記載してください"
      placeholder: "例: シリーズB向け投資家リストを作成し、10社へのアプローチを完了する"
    validations:
      required: true

  - type: input
    id: kpi_summary
    attributes:
      label: "📊 KPI / 指標"
      description: "このタスクが影響する主要指標を簡潔に記載してください"
      placeholder: "例: Qualified Leads +20件、MOU 締結数 3社、採用応募数 15件"
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "✅ Acceptance Criteria"
      description: "タスクの完了条件を具体的に記載してください"
      placeholder: |
        例:
        - [ ] 投資家リスト (Google Sheets) を共有
        - [ ] 全候補へピッチ資料送付
        - [ ] 1st ミーティング日程が 5 社確定
    validations:
      required: true

  - type: textarea
    id: deliverables
    attributes:
      label: "📦 Deliverables"
      description: "成果物のリンクを記載してください（完了時に更新）"
      placeholder: |
        例:
        - Notion: https://www.notion.so/...
        - Drive: https://drive.google.com/...
        - Slide: https://docs.google.com/presentation/...

  - type: textarea
    id: dependencies
    attributes:
      label: "🔗 Dependencies"
      description: "関連 Issue があれば記載してください"
      placeholder: |
        例:
        - Blocks: #123, #456
        - Blocked by: #789
        - Related: #012

  - type: dropdown
    id: task_type
    attributes:
      label: "🏷️ タスク種別"
      description: "該当するタスク種別を選択してください（複数ある場合は後でラベルを追加）"
      options:
        - "sales (営業)"
        - "marketing (マーケティング)"
        - "partnership (パートナーシップ)"
        - "finance (財務)"
        - "legal (法務)"
        - "hr (人事・採用)"
        - "ops (総務・オペレーション)"
        - "research (調査・レポート)"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "⚡ 優先度"
      description: "タスクの優先度を選択してください"
      options:
        - "p0 (高)"
        - "p1 (中)"
        - "p2 (低)"
    validations:
      required: true

  - type: textarea
    id: additional_notes
    attributes:
      label: "📝 Additional Notes"
      description: "その他補足事項があれば記載してください"
      placeholder: "参考資料、ステークホルダー、リスクなど"

  - type: checkboxes
    id: confirmation
    attributes:
      label: 確認事項
      description: Issue作成後、以下の項目をご確認ください
      options:
        - label: Assignee が設定されている
          required: true
        - label: GitHub Projects ボードに追加されている
          required: true
        - label: Status ラベルが設定されている（todo / in-progress / review / done）
          required: true
        - label: Priority ラベルが設定されている（p0 / p1 / p2）
          required: true
        - label: Start Date と End Date が設定されている
          required: true

  - type: markdown
    attributes:
      value: |
        ---

        ## 🗂️ ストレージポリシー

        成果物は以下のルールに従って保存してください：
        - **Google Drive**: 契約書・資料 `/Sales|Legal|Finance/<folder>` 形式
        - **Notion**: 1 ドキュメント = 1 Notion ページ、URL を Issue に貼付

        ⚠️ **重要**: Issue にリンクされていないものは存在しません。必ず URL を記載してください。
